---
- name: "selinux agent"
  hosts: all
  tasks:
  - name: "Collect selinux audit logs"
    vars:
      - selinux_api: "http://ignite.openknowit.com/selinux"
    include_role:
      name: ign8_ansible_role_selinux
  become: true
